# STRMBASE - DirectShow Base Classes
#
# STRMBASE_FOUND
# STRMBASE_INCLUDE_DIRS
# STRMBASE_LIBRARIES

IF(WIN32)

	FIND_PATH(STRMBASE_INCLUDE_DIRS streams.h ${DEPMAN_PATH}/include)
	FIND_LIBRARY(STRMBASE_LIBRARIES strmbase ${DEPMAN_PATH}/lib)
	MARK_AS_ADVANCED(STRMBASE_INCLUDE_DIRS STRMBASE_LIBRARIES)
	IF(STRMBASE_INCLUDE_DIRS AND STRMBASE_LIBRARIES)
		SET(STRMBASE_FOUND 1)
	ENDIF(STRMBASE_INCLUDE_DIRS AND STRMBASE_LIBRARIES)

ENDIF(WIN32)

