# Locate Okode::Frameworks
# This module defines
# OKODEFRAMEWORKS_LIBRARIES
# OKODEFRAMEWORKS_LIBRARIES_DEBUG
# OKODEFRAMEWORKS_FOUND, if false, do not try to link to Okode::Frameworks
# OKODEFRAMEWORKS_INCLUDE_DIR, where to find the headers

FIND_PATH(OKODEFRAMEWORKS_INCLUDE_DIR okode/base/Referenced.hpp)

FIND_LIBRARY(OKODEFRAMEWORKS_BASE_LIBRARY okode.base)
FIND_LIBRARY(OKODEFRAMEWORKS_BASE_LIBRARY_DEBUG okode.based)

FIND_LIBRARY(OKODEFRAMEWORKS_MEDIA_LIBRARY okode.media)
FIND_LIBRARY(OKODEFRAMEWORKS_MEDIA_LIBRARY_DEBUG okode.mediad)

FIND_LIBRARY(OKODEFRAMEWORKS_NODEKIT_LIBRARY okode.nodekit)
FIND_LIBRARY(OKODEFRAMEWORKS_NODEKIT_LIBRARY_DEBUG okode.nodekitd)

SET(OKODEFRAMEWORKS_FOUND "NO")
IF(OKODEFRAMEWORKS_INCLUDE_DIR AND OKODEFRAMEWORKS_BASE_LIBRARY AND OKODEFRAMEWORKS_BASE_LIBRARY_DEBUG AND OKODEFRAMEWORKS_MEDIA_LIBRARY AND OKODEFRAMEWORKS_MEDIA_LIBRARY_DEBUG AND OKODEFRAMEWORKS_NODEKIT_LIBRARY AND OKODEFRAMEWORKS_NODEKIT_LIBRARY_DEBUG)

	SET(OKODEFRAMEWORKS_FOUND "YES")
	SET(OKODEFRAMEWORKS_LIBRARIES
		${OKODEFRAMEWORKS_BASE_LIBRARY}
		${OKODEFRAMEWORKS_MEDIA_LIBRARY}
		${OKODEFRAMEWORKS_NODEKIT_LIBRARY}
	)
	SET(OKODEFRAMEWORKS_LIBRARIES_DEBUG
		${OKODEFRAMEWORKS_BASE_LIBRARY_DEBUG}
		${OKODEFRAMEWORKS_MEDIA_LIBRARY_DEBUG}
		${OKODEFRAMEWORKS_NODEKIT_LIBRARY_DEBUG}
	)
	MARK_AS_ADVANCED(OKODEFRAMEWORKS_INCLUDE_DIR OKODEFRAMEWORKS_BASE_LIBRARY OKODEFRAMEWORKS_MEDIA_LIBRARY OKODEFRAMEWORKS_NODEKIT_LIBRARY)
	MARK_AS_ADVANCED(OKODEFRAMEWORKS_BASE_LIBRARY_DEBUG OKODEFRAMEWORKS_MEDIA_LIBRARY_DEBUG OKODEFRAMEWORKS_NODEKIT_LIBRARY_DEBUG)

ENDIF(OKODEFRAMEWORKS_INCLUDE_DIR AND OKODEFRAMEWORKS_BASE_LIBRARY AND OKODEFRAMEWORKS_BASE_LIBRARY_DEBUG AND OKODEFRAMEWORKS_MEDIA_LIBRARY AND OKODEFRAMEWORKS_MEDIA_LIBRARY_DEBUG AND OKODEFRAMEWORKS_NODEKIT_LIBRARY AND OKODEFRAMEWORKS_NODEKIT_LIBRARY_DEBUG)

