# INTTYPES - inttypes.h for Windows platform
#
# INTTYPES_FOUND
# INTTYPES_INCLUDE_DIR

IF(WIN32)

	FIND_PATH(INTTYPES_INCLUDE_DIR inttypes.h ${DEPMAN_PATH}/include)
	MARK_AS_ADVANCED(INTTYPES_INCLUDE_DIR)
	IF(INTTYPES_INCLUDE_DIR)
		SET(INTTYPES_FOUND 1)
	ENDIF(INTTYPES_INCLUDE_DIR)

ENDIF(WIN32)

