# Locate FreeType
# This module defines
# FREETYPE_LIBRARY
# FREETYPE_FOUND, if false, do not try to link to FreeType
# FREETYPE_INCLUDE_DIRS, where to find the headers

FIND_PATH(FREETYPE_INCLUDE_DIR_ft2build ft2build.h 
)
MARK_AS_ADVANCED(FREETYPE_INCLUDE_DIR_ft2build)

FIND_PATH(FREETYPE_INCLUDE_DIR_freetype2 freetype/config/ftheader.h 
	/usr/include/freetype2
	/usr/X11R6/include/freetype2
)
MARK_AS_ADVANCED(FREETYPE_INCLUDE_DIR_freetype2)

FIND_LIBRARY(FREETYPE_LIBRARY 
	NAMES freetype
)
MARK_AS_ADVANCED(FREETYPE_LIBRARY)

IF(FREETYPE_INCLUDE_DIR_ft2build AND FREETYPE_INCLUDE_DIR_freetype2)
	SET(FREETYPE_INCLUDE_DIRS "${FREETYPE_INCLUDE_DIR_ft2build};${FREETYPE_INCLUDE_DIR_freetype2}")
ENDIF(FREETYPE_INCLUDE_DIR_ft2build AND FREETYPE_INCLUDE_DIR_freetype2)

SET(FREETYPE_FOUND "NO")
IF(FREETYPE_LIBRARY AND FREETYPE_INCLUDE_DIRS)
	SET(FREETYPE_FOUND "YES")
ENDIF(FREETYPE_LIBRARY AND FREETYPE_INCLUDE_DIRS)


